### ISSUE TITLE
The provided key element does not match the schema

### ISSUE THREAD

**Issue by gconcepts** [matheussilvasantos/dynamocli#1] opened 2019-08-07 17:16 UTC
I'm getting the below exception when trying to push data from a CSV to a dynamodb table

{code}
USD1601311:DataGenerator ooshiber$ dynamocli import APIReleases.csv --table ethos-affinity-api-releases
/Library/Ruby/Gems/2.3.0/gems/aws-sdk-core-3.62.0/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call': The provided key element does not match the schema (Aws::DynamoDB::Errors::ValidationException)
	from /Library/Ruby/Gems/2.3.0/gems/aws-sdk-dynamodb-1.34.0/lib/aws-sdk-dynamodb/plugins/simple_attributes.rb:117:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/aws-sdk-core-3.62.0/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/aws-sdk-core-3.62.0/lib/aws-sdk-core/plugins/idempotency_token.rb:17:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/aws-sdk-core-3.62.0/lib/aws-sdk-core/plugins/param_converter.rb:24:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/aws-sdk-core-3.62.0/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/aws-sdk-core-3.62.0/lib/seahorse/client/plugins/response_target.rb:23:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/aws-sdk-core-3.62.0/lib/seahorse/client/request.rb:70:in `send_request'
	from /Library/Ruby/Gems/2.3.0/gems/aws-sdk-dynamodb-1.34.0/lib/aws-sdk-dynamodb/client.rb:823:in `batch_write_item'
	from /Library/Ruby/Gems/2.3.0/gems/dynamocli-0.1.4/lib/dynamocli/import.rb:45:in `block in write_records_to_dynamodb_table'
	from /Library/Ruby/Gems/2.3.0/gems/dynamocli-0.1.4/lib/dynamocli/import.rb:44:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/dynamocli-0.1.4/lib/dynamocli/import.rb:44:in `each_slice'
	from /Library/Ruby/Gems/2.3.0/gems/dynamocli-0.1.4/lib/dynamocli/import.rb:44:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/dynamocli-0.1.4/lib/dynamocli/import.rb:44:in `write_records_to_dynamodb_table'
	from /Library/Ruby/Gems/2.3.0/gems/dynamocli-0.1.4/lib/dynamocli/import.rb:18:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/dynamocli-0.1.4/lib/dynamocli.rb:17:in `import'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/dynamocli-0.1.4/bin/dynamocli:6:in `<top (required)>'
	from /usr/local/bin/dynamocli:22:in `load'
	from /usr/local/bin/dynamocli:22:in `<main>'
{code}

My dynamodb table looks as below
{code}
![image](https://user-images.githubusercontent.com/15819441/62643160-526f7a00-b915-11e9-8860-c38711b5e5d9.png)
{code}

The data in the CSV looks like below
{code}
releaseId,releaseName,releaseVersion
1,Test,1.17.0
2,Test,1.18.0
3,Test,1.19.0
4,Test,1.20.0
5,Test,1.21.0
{code}

What do you think could be the issue?

**Comment by matheussilvasantos** [comment] 2019-08-08 14:24
Thank you for reporting this issue.

I was able to reproduce your error, the problem was that the program wasn't converting the data to the right type of data, in other words, the same type defined for the keys in the DynamoDB table.

I've just released a new version, could you test if it is working? It is the version 0.1.5.

**Comment by gconcepts** [comment] 2019-08-08 14:25
Thanks. Will try that out now and report back.

**Comment by gconcepts** [comment] 2019-08-08 14:40
I still seem to be getting the same error and I even uninstalled the older version and installed the new one.

**Comment by matheussilvasantos** [comment] 2019-08-08 15:04
What you see when you run `gem list dynamocli`?

**Comment by gconcepts** [comment] 2019-08-08 15:08
gem list dynamocli

*** LOCAL GEMS ***

dynamocli (0.1.5)

**Comment by matheussilvasantos** [comment] 2019-08-08 18:13
That's weird, could you paste the error again?

**Comment by gconcepts** [comment] 2019-08-08 18:14
dynamocli import APIReleases.csv --table ethos-affinity-api-releases
/Library/Ruby/Gems/2.3.0/gems/aws-sdk-core-3.62.0/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call': The provided key element does not match the schema (Aws::DynamoDB::Errors::ValidationException)
	from /Library/Ruby/Gems/2.3.0/gems/aws-sdk-dynamodb-1.34.0/lib/aws-sdk-dynamodb/plugins/simple_attributes.rb:117:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/aws-sdk-core-3.62.0/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/aws-sdk-core-3.62.0/lib/aws-sdk-core/plugins/idempotency_token.rb:17:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/aws-sdk-core-3.62.0/lib/aws-sdk-core/plugins/param_converter.rb:24:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/aws-sdk-core-3.62.0/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/aws-sdk-core-3.62.0/lib/seahorse/client/plugins/response_target.rb:23:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/aws-sdk-core-3.62.0/lib/seahorse/client/request.rb:70:in `send_request'
	from /Library/Ruby/Gems/2.3.0/gems/aws-sdk-dynamodb-1.34.0/lib/aws-sdk-dynamodb/client.rb:823:in `batch_write_item'
	from /Library/Ruby/Gems/2.3.0/gems/dynamocli-0.1.5/lib/dynamocli/import.rb:59:in `block in write_records_to_dynamodb_table'
	from /Library/Ruby/Gems/2.3.0/gems/dynamocli-0.1.5/lib/dynamocli/import.rb:58:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/dynamocli-0.1.5/lib/dynamocli/import.rb:58:in `each_slice'
	from /Library/Ruby/Gems/2.3.0/gems/dynamocli-0.1.5/lib/dynamocli/import.rb:58:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/dynamocli-0.1.5/lib/dynamocli/import.rb:58:in `write_records_to_dynamodb_table'
	from /Library/Ruby/Gems/2.3.0/gems/dynamocli-0.1.5/lib/dynamocli/import.rb:19:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/dynamocli-0.1.5/lib/dynamocli.rb:17:in `import'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/dynamocli-0.1.5/bin/dynamocli:6:in `<top (required)>'
	from /usr/local/bin/dynamocli:22:in `load'
	from /usr/local/bin/dynamocli:22:in `<main>'

**Comment by matheussilvasantos** [comment] 2019-08-08 18:19
Does your table have some index?

**Comment by gconcepts** [comment] 2019-08-08 18:20
Yes it does have an index. I will try deleting the index and try it out again.

**Comment by gconcepts** [comment] 2019-08-08 18:24
Same error with the index deleted. Will wait a bit in case AWS index deletion is still synching

**Comment by gconcepts** [comment] 2019-08-08 18:30
Same error. Does it work for you?

**Comment by matheussilvasantos** [comment] 2019-08-08 18:32
Yes, it does :cry:.

![image](https://user-images.githubusercontent.com/14128874/62728267-bc5d5180-b9f1-11e9-95b6-a9c917175d91.png)

**Comment by gconcepts** [comment] 2019-08-08 18:33
Weird. Let me delete the table and recreate without the index and i'll see if it works

**Comment by gconcepts** [comment] 2019-08-08 18:37
Same error still. Can you send me a screenshot of your table overview page?

**Comment by matheussilvasantos** [comment] 2019-08-08 18:45
Here it is:
![image](https://user-images.githubusercontent.com/14128874/62729060-8faa3980-b9f3-11e9-86c3-e737338a1bba.png)

**Comment by gconcepts** [comment] 2019-08-08 18:56
This is baffling. Still getting the same error after recreating the table. Are you on a Mac?

**Comment by matheussilvasantos** [comment] 2019-08-08 19:08
No, I'm running Linux.

**Comment by matheussilvasantos** [comment] 2019-08-08 19:12
Maybe Ruby is not running the right version, you can try cloning the repository and execute in the repository folder `./bin/dynamocli import APIReleases.csv --to ethos-affinity-api-releases`

**Comment by gconcepts** [comment] 2019-08-08 19:14
Ok. Will try that out and keep you posted

**Comment by gconcepts** [comment] 2019-08-08 19:20
Same error. I will try it out from a linux VM and see if the same error occurs. Will keep you updated.

**Comment by gconcepts** [comment] 2019-08-09 15:30
Same error on a Linux based distro.

**Comment by matheussilvasantos** [comment] 2019-08-10 15:08
It doesn't make much sense but maybe can be your credentials, what permissions your machine have on AWS?

**Comment by gconcepts** [comment] 2019-08-13 14:19
The same account has full admin permission in AWS. I can use the same account to perform the tasks manually within AWS console

**Comment by AntonERG** [comment] 2019-11-14 23:23
Hey guys, I have a same issue, already checked permissions and creds. Any solution?
(I'm also working on Mac)

**Comment by matheussilvasantos** [comment] 2019-11-15 12:33
Hi, could you post the error here too?

**Comment by AntonERG** [comment] 2019-11-15 18:26
Antons-MacBook-Pro:iosbaliblogger admin$ dynamocli import aeguides-baliblogger-main.csv --to aeguides-baliblogger-main
Traceback (most recent call last):
	22: from /usr/local/bin/dynamocli:23:in `<main>'
	21: from /usr/local/bin/dynamocli:23:in `load'
	20: from /Library/Ruby/Gems/2.6.0/gems/dynamocli-0.1.5/bin/dynamocli:6:in `<top (required)>'
	19: from /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	18: from /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	17: from /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	16: from /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	15: from /Library/Ruby/Gems/2.6.0/gems/dynamocli-0.1.5/lib/dynamocli.rb:17:in `import'
	14: from /Library/Ruby/Gems/2.6.0/gems/dynamocli-0.1.5/lib/dynamocli/import.rb:19:in `start'
	13: from /Library/Ruby/Gems/2.6.0/gems/dynamocli-0.1.5/lib/dynamocli/import.rb:58:in `write_records_to_dynamodb_table'
	12: from /Library/Ruby/Gems/2.6.0/gems/dynamocli-0.1.5/lib/dynamocli/import.rb:58:in `each'
	11: from /Library/Ruby/Gems/2.6.0/gems/dynamocli-0.1.5/lib/dynamocli/import.rb:58:in `each_slice'
	10: from /Library/Ruby/Gems/2.6.0/gems/dynamocli-0.1.5/lib/dynamocli/import.rb:58:in `each'
	 9: from /Library/Ruby/Gems/2.6.0/gems/dynamocli-0.1.5/lib/dynamocli/import.rb:59:in `block in write_records_to_dynamodb_table'
	 8: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-dynamodb-1.38.0/lib/aws-sdk-dynamodb/client.rb:816:in `batch_write_item'
	 7: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.77.0/lib/seahorse/client/request.rb:70:in `send_request'
	 6: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.77.0/lib/seahorse/client/plugins/response_target.rb:23:in `call'
	 5: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.77.0/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
	 4: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.77.0/lib/aws-sdk-core/plugins/param_converter.rb:24:in `call'
	 3: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.77.0/lib/aws-sdk-core/plugins/idempotency_token.rb:17:in `call'
	 2: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.77.0/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
	 1: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-dynamodb-1.38.0/lib/aws-sdk-dynamodb/plugins/simple_attributes.rb:117:in `call'
/Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.77.0/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call': The provided key element does not match the schema (Aws::DynamoDB::Errors::ValidationException)
Antons-MacBook-Pro:iosbaliblogger admin$

**Comment by AntonERG** [comment] 2019-11-15 18:28
Just for testing I:
- added item to dynamodb manually via aws web console
- made an export to csv of created item
- changed value of primary key in csv and tried to import it using ur tool
So, I hope the csv file format should be correct.

Really like ur tool, hope you will be able to fix this issue=)

**Comment by matheussilvasantos** [comment] 2019-11-22 11:48
Hi, thanks for the feedback.

I've followed the steps you provided and now I know why it's crashing.

That is the header from the CSV exported from AWS Web Console:

```csv
"id (N)","name (S)","age (N)","source (S)","tree (S)"
```

`dynamocli` expects the exact name of the field and here we have `id (N)` instead of `id`.

I suggest you edit the header of the CSV file by now because I don't know if it is a good idea to remove the ` (N)` part on my tool. I'll think about it and let you know if I implement it. You can give suggestions if you want :smile:.

**Comment by AntonERG** [comment] 2019-11-22 14:49
Heey Matheus! Thanks for reply, now works like a charm 🎉

Well, you know it might be no need to add support of "id (S)" style header, but it might be useful if you put a chapter in Readme.md with an example of correct header and csv file format.

Still, it is a case that lots of people will try to use Export csv feature from AWS console and after look for solution to import it. To change header line in csv by hands is not a problem at all, but it's nice to know that you have to do it =))

**Comment by sergiorodriguez82** [comment] 2019-12-16 19:18
Adjusting the headers worked!
Nice work, Update your usage instructions to consider this scenario. I think is the most frequent!

**Comment by matheussilvasantos** [comment] 2020-01-13 23:32
I've made a new release. Now, it is possible to call `dynamocli import` passing the option `--exported-from-aws`. This will modify the header.  I hope you enjoy. :smile:.

**Comment by matheussilvasantos** [comment] 2020-01-13 23:35
Closing this issue.

**Closed as completed by matheussilvasantos** 2020-01-13 23:35 UTC
Labels: bug
